### ISSUE TITLE
URL pour le callback erronée

### ISSUE THREAD

**Issue by spamoi33** [lunarok/jeedom_sigfox#4]
Bonjour,

L'URL générée automatiquement par le plugin est erronée, il faut remplacer "api" par "apikey".

Exemple: 

NOK: https://YYYYYY/plugins/sigfox/core/api/jeeSigfox.php?api=XXX&id={device}&time={time}&rssi={rssi}&data={data}
OK: NOK: https://YYYYYY/plugins/sigfox/core/api/jeeSigfox.php?apikey=XXX&id={device}&time={time}&rssi={rssi}&data={data}

Merci.

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_sigfox/commit/ed23e9e07af5f2ce05d4ba88f2cca0b2eaf9c619
